// import { Inter } from "next/font/google";
import "./globals.css";
// import Home from "./page";
import { Navbar } from "./components";
// import SingleInvoice from "./aboutinvoice/[id]/page";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
// export const revalidate=0

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className="flex flex-col h-full">
        <Navbar />
        <main className="col-span-6"> {children}</main>
      </body>
    </html>
  );
}
