import { Inter } from "next/font/google";
import "./globals.css";
// import Home from "./page";

import Restangle from "./components/Restangle";

import Drawer from "./components/Drawer";
import GlobalProvider from "@/globalProvider";
import { InvoiceLilst } from "./components";
// import SingleInvoice from "./aboutinvoice/[id]/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Invoice",
  description: "Generated by create next app",
};
export const revalidate = 0;

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className={`${inter.className}  `}>
        <GlobalProvider>
          <Restangle />
          <Drawer />

          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
